### ISSUE TITLE
Adding a "Run" button to the Schedule Entry items

### ISSUE THREAD

**Issue by jbatterman** [opendcs/opendcs#188] opened 2023-02-23 15:07 UTC
**Is your feature request related to a problem? Please describe.**
Currently to test new routing specs on the routing-scheduler, I need to create a new one that pipes to shefit so I can run it on the server, or I need to set the execution schedule to run every 5 minutes, so I can check the log after 5 minutes (for example).  There may be a better way to do this that I'm just not aware of, but this has been cumbersome and it doesn't seem like the routing-scheduler always sees my changes to the execution schedule.

**Describe the solution you'd like**
Would be nice to have a "Run" button at the bottom of the Schedule Entry item to manually run a data pull and have an output log, similar to having the "Run Computations" button in the Computation Editor.

**Comment by MikeNeilson** [comment] 2023-02-23 15:12
Duplicate of #48. Please review and add additional comments on that ticket.

**Closed by MikeNeilson** 2023-02-23 15:12 UTC
