### ISSUE TITLE
Create Screening ID   Variable Time Selection

### ISSUE THREAD

**Issue by wdproctor** [opendcs/opendcs#351] opened 2023-10-26 16:56 UTC
**Is your feature request related to a problem? Please describe.**
The new app for creating screening IDs looks great, but can it be modified to change the "rate of change" periods from just hourly to being daily (for daily data) or 15 minute, for 15 minute data.

**Comment by MikeNeilson** [comment] 2023-10-26 16:58
duplicate of #176

**Closed by MikeNeilson** 2023-10-26 16:58 UTC
Labels: feature, request
