### ISSUE TITLE
showCompDepends | grep Location - SLF4J errors

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#169] opened 2023-01-25 20:55 UTC
**Describe the bug**
I don't know if this is a bug - but the following shows up when I run showCompDepends | grep Location now:

h7dcsa05@coe-lreuwa04lre:/wm/lre/h7dcsa05/bin > showCompDepends | grep MichHuronBasin
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I tried it for multiple locations, and have tried rebooting DCS.  

**Desktop/ServerSide (please complete the following information):**
- OPENDCS version 7.0.4

**Additional context**
Wanted to bring this to your attention so that it doesn't become a greater issue

**Comment by MikeNeilson** [comment] 2023-01-25 20:58
That's not a bug, the slf4j library was pulled in by one of the dependencies and is trying to start a logger but can't find anything. That message can be safely ignored.

We will figure how a way to suppress it, but it's a low priority.

**Comment by MikeNeilson** [comment] 2023-08-16 16:14
Fixed in [#236](https://github.com/opendcs/opendcs/pull/236)

**Closed by MikeNeilson** 2023-08-16 16:14 UTC
Labels: bug, priority-low
