### ISSUE TITLE
Opening computation details from list opens the wrong one if sorted

### ISSUE THREAD

**Issue by DanielTOsborne** [opendcs/opendcs#261] opened 2023-07-21 17:27 UTC
**Describe the bug**
If you try to open computation details from the list, it opens the wrong one.

**To Reproduce**
1. Open Compedit
2. Click 'Computations' tab
3. Click the 'Name' column to sort computations by name.
4. Double-click on a computation.
5. Notice the one you opened is the wrong one.

**Expected behavior**
The computation opened should match the one visually selected, no matter how its sorted.

**Screenshots**
![image](https://github.com/opendcs/opendcs/assets/73709911/2088049e-1e4d-47aa-b93d-63cc3e8b5722)
![image](https://github.com/opendcs/opendcs/assets/73709911/6c70ab41-f92c-4fdb-a616-a50cf34515dc)
![image](https://github.com/opendcs/opendcs/assets/73709911/a9e87054-f4b5-437a-8ad1-47799c28e805)
![image](https://github.com/opendcs/opendcs/assets/73709911/41479b08-58c2-4d4f-99e2-b7dcf45d3f12)

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version: 7.0.8-guifix

**Comment by DanielTOsborne** [comment] 2023-07-21 17:32
I originally thought this was another bug, but upon closer inspection I realized it's actually a different issue. I've renamed this issue and adjusted the description accordingly.

**Comment by hoffmanjs** [comment] 2023-08-01 16:16
This issue was fixed with #252.

**Comment by MikeNeilson** [comment] 2023-08-01 16:21
Duplicate of #252

**Closed by MikeNeilson** 2023-08-01 16:21 UTC
